language: nix

sudo: false

matrix:
  include:
    - env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
    - env: NIX_CHANNEL=https://nixos.org/channels/nixos-19.09

install:
 - nix --version
 - nix-channel --add "${NIX_CHANNEL}" nixpkgs
 - travis_retry nix-channel --update

script:
 - nix-build

